# Generated by Django 6.0.1 on 2026-01-23 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(max_length=15, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.CharField(max_length=30, verbose_name='Número da Casa/Apto'),
        ),
    ]
