# Generated by Django 6.0.1 on 2026-01-23 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0002_alter_visitante_cpf_alter_visitante_numero_casa'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Saída'),
        ),
    ]
