# Generated by Django 6.0.1 on 2026-01-23 03:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0003_visitante_horario_saida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Morador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=190, verbose_name='Nome do Morador')),
                ('cpf', models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF')),
                ('telefone', models.CharField(max_length=20, verbose_name='Telefone de Contato')),
                ('bloco', models.CharField(blank=True, max_length=10, null=True, verbose_name='Bloco')),
                ('apartamento', models.CharField(max_length=10, verbose_name='Número do Apartamento')),
            ],
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(max_length=14, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número da Casa/Apto (Antigo)'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='morador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portaria.morador', verbose_name='Morador Responsável'),
        ),
    ]
