# Generated by Django 6.0.1 on 2026-01-23 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0004_morador_alter_visitante_cpf_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'verbose_name_plural': 'Moradores'},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={'verbose_name_plural': 'Visitantes'},
        ),
    ]
