# Generated by Django 6.0.1 on 2026-02-27 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0004_areacomum_taxa_reserva_alter_areacomum_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ocorrencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('infrator', models.CharField(blank=True, max_length=200, verbose_name='Possível Infrator/Unidade')),
                ('descricao', models.TextField(verbose_name='Descrição da Ocorrência')),
                ('status', models.CharField(choices=[('REGISTRADA', 'Registrada'), ('EM_ANALISE', 'Em Análise'), ('RESOLVIDA', 'Resolvida')], default='REGISTRADA', max_length=20, verbose_name='Status')),
                ('data_registro', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias_registradas', to='portaria.morador', verbose_name='Autor da Ocorrência')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ocorrencias', to='portaria.condominio')),
            ],
            options={
                'verbose_name': 'Ocorrência',
                'verbose_name_plural': 'Ocorrências',
                'ordering': ['-data_registro'],
            },
        ),
    ]
