# Generated by Django 6.0.1 on 2026-01-23 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0005_alter_morador_options_alter_visitante_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitante',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
    ]
