# Generated by Django 6.0.1 on 2026-01-23 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0006_alter_visitante_data_nascimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitante',
            name='observacoes',
            field=models.TextField(blank=True, verbose_name='Observações'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='quem_autorizou',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quem Autorizou'),
        ),
    ]
