# Generated by Django 6.0.1 on 2026-02-27 03:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0006_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='resposta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='portaria.mensagem', verbose_name='Em resposta a'),
        ),
    ]
