# Generated by Django 6.0.1 on 2026-01-23 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0007_visitante_observacoes_visitante_quem_autorizou'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encomenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_chegada', models.DateTimeField(auto_now_add=True, verbose_name='Data de Chegada')),
                ('volume', models.CharField(help_text='Ex: Caixa Amazon, Envelope, Ifood...', max_length=100, verbose_name='Volume')),
                ('entregue', models.BooleanField(default=False, verbose_name='Já foi entregue?')),
                ('data_entrega', models.DateTimeField(blank=True, null=True, verbose_name='Data da Entrega')),
                ('quem_retirou', models.CharField(blank=True, max_length=100, verbose_name='Quem retirou?')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.morador', verbose_name='Para o Morador')),
            ],
            options={
                'verbose_name_plural': 'Encomendas',
            },
        ),
    ]
