# Generated by Django 6.0.1 on 2026-01-24 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0008_encomenda'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='notificado',
            field=models.BooleanField(default=False, verbose_name='Morador foi avisado?'),
        ),
    ]
