# Generated by Django 6.0.1 on 2026-01-24 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0009_encomenda_notificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='documento_retirada',
            field=models.CharField(blank=True, max_length=50, verbose_name='Documento de quem retirou'),
        ),
    ]
