# Generated by Django 6.0.1 on 2026-01-24 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0010_encomenda_documento_retirada'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='porteiro_cadastro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cadastrou_encomenda', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='encomenda',
            name='porteiro_entrega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregou_encomenda', to=settings.AUTH_USER_MODEL),
        ),
    ]
