# Generated by Django 6.0.1 on 2026-01-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0011_encomenda_porteiro_cadastro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='destinatario_alternativo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Destinatário Externo (A/C)'),
        ),
    ]
