# Generated by Django 6.0.1 on 2026-01-24 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0012_encomenda_destinatario_alternativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RECLAMACAO', '📢 Reclamação'), ('MANUTENCAO', '🛠️ Manutenção'), ('MUDANCA', '🚚 Mudança'), ('RESERVA', '📅 Reserva de Espaço'), ('OUTRO', '📝 Outro')], max_length=20, verbose_name='Tipo de Solicitação')),
                ('descricao', models.TextField(verbose_name='Descrição do Pedido')),
                ('status', models.CharField(choices=[('PENDENTE', '🟠 Pendente'), ('EM_ANALISE', '🔵 Em Análise'), ('APROVADO', '🟢 Aprovado / Resolvido'), ('NEGADO', '🔴 Negado / Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status Atual')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Registro')),
                ('resposta_admin', models.TextField(blank=True, verbose_name='Resposta da Administração')),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
                ('morador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.morador', verbose_name='Morador Solicitante')),
            ],
            options={
                'verbose_name': 'Solicitação / Ocorrência',
                'verbose_name_plural': 'Solicitações e Ocorrências',
            },
        ),
    ]
