# Generated by Django 6.0.1 on 2026-03-22 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0012_documentocondominio'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='condominios',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='portaria.condominio'),
        ),
    ]
