# Generated by Django 6.0.1 on 2026-01-24 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0013_solicitacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='encomenda',
            options={},
        ),
        migrations.AlterModelOptions(
            name='morador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='visitante',
            options={},
        ),
        migrations.AddField(
            model_name='visitante',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Porteiro Responsável'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='entregue',
            field=models.BooleanField(default=False, verbose_name='Entregue?'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='morador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.morador', verbose_name='Morador'),
        ),
        migrations.AlterField(
            model_name='encomenda',
            name='volume',
            field=models.CharField(max_length=50, verbose_name='Volume'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='apartamento',
            field=models.CharField(max_length=10, verbose_name='Apartamento'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='bloco',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='Bloco'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='morador',
            name='cpf',
            field=models.CharField(blank=True, default='', max_length=14, verbose_name='CPF'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='morador',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='morador',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cpf',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='horario_chegada',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Horário de Chegada'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='horario_saida',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Horário de Saída'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='morador_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.morador', verbose_name='Morador Responsável'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='nome_completo',
            field=models.CharField(max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='numero_casa',
            field=models.CharField(blank=True, max_length=10, verbose_name='Número da Casa/Apto (Antigo)'),
        ),
        migrations.AlterField(
            model_name='visitante',
            name='placa_veiculo',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Placa do Veículo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='visitante',
            name='quem_autorizou',
            field=models.CharField(blank=True, max_length=100, verbose_name='Quem Autorizou?'),
        ),
    ]
