# Generated by Django 6.0.1 on 2026-02-06 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0014_alter_encomenda_options_alter_morador_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitacao',
            name='status',
            field=models.CharField(choices=[('PENDENTE', '🟡 Pendente'), ('EM_ANDAMENTO', '🔵 Em Andamento'), ('CONCLUIDO', '🟢 Concluído'), ('CANCELADO', '🔴 Cancelado')], default='PENDENTE', max_length=20, verbose_name='Status Atual'),
        ),
    ]
