# Generated by Django 6.0.1 on 2026-02-07 01:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0016_portal_morador'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Condomínio')),
                ('endereco', models.CharField(blank=True, max_length=200, verbose_name='Endereço')),
                ('cnpj', models.CharField(blank=True, max_length=18, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('logo', models.ImageField(blank=True, upload_to='condominios/', verbose_name='Logo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'ordering': ['nome'],
            },
        ),
        migrations.AddField(
            model_name='morador',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio', verbose_name='Condomínio'),
        ),
        migrations.CreateModel(
            name='Sindico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('telefone', models.CharField(blank=True, max_length=20, verbose_name='Telefone')),
                ('condominios', models.ManyToManyField(related_name='sindicos', to='portaria.condominio', verbose_name='Condomínios Gerenciados')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sindico', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Síndico',
                'verbose_name_plural': 'Síndicos',
            },
        ),
    ]
