# Generated by Django 6.0.1 on 2026-02-10 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0017_condominio_morador_condominio_sindico'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avisos', to='portaria.condominio', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='data_expiracao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Expiração'),
        ),
        migrations.AddField(
            model_name='aviso',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='avisos/%Y/%m/', verbose_name='Imagem'),
        ),
    ]
