# Generated by Django 6.0.1 on 2026-04-21 01:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0018_customuser_receber_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='receber_push',
            field=models.BooleanField(default=False, verbose_name='Permitir Push'),
        ),
        migrations.CreateModel(
            name='TarefaSindico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255, verbose_name='Descrição da Tarefa')),
                ('concluida', models.BooleanField(default=False, verbose_name='Concluída')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarefas_sindico', to='portaria.condominio')),
            ],
            options={
                'verbose_name': 'Tarefa do Síndico',
                'verbose_name_plural': 'Tarefas do Síndico',
                'ordering': ['concluida', '-criado_em'],
            },
        ),
    ]
