# Generated by Django 6.0.1 on 2026-04-27 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0019_alter_customuser_receber_push_tarefasindico'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackMorador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Sugestão', 'Sugestão'), ('Elogio', 'Elogio'), ('Crítica', 'Crítica')], max_length=20)),
                ('assunto', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('foto', models.FileField(blank=True, null=True, upload_to='feedbacks/%Y/%m/')),
                ('data_envio', models.DateTimeField(auto_now_add=True)),
                ('anonimo', models.BooleanField(default=False)),
                ('lido_pela_gestao', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='portaria.condominio')),
                ('morador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feedbacks', to='portaria.morador')),
            ],
            options={
                'verbose_name': 'Feedback / Sugestão',
                'verbose_name_plural': 'Feedbacks e Sugestões',
                'ordering': ['-data_envio'],
            },
        ),
    ]
