# Generated by Django 6.0.1 on 2026-02-19 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0020_notificacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aviso',
            name='arquivo',
            field=models.FileField(blank=True, upload_to='avisos/anexos/%Y/%m/', verbose_name='Arquivo Anexo'),
        ),
    ]
