# Generated by Django 6.0.1 on 2026-04-30 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0020_feedbackmorador'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='acesso_liberado',
            field=models.BooleanField(default=False, verbose_name='Acesso Liberado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='bloco_apto_liberado',
            field=models.CharField(blank=True, max_length=30, verbose_name='Bloco/Apto liberado'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='data_liberacao',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data/Hora da Liberação'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='documento_liberado',
            field=models.CharField(blank=True, max_length=30, verbose_name='RG/CPF de quem acessou'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='nome_liberado',
            field=models.CharField(blank=True, max_length=150, verbose_name='Nome de quem acessou'),
        ),
    ]
