# Generated by Django 6.0.1 on 2026-05-05 17:54

import django.db.models.deletion
import portaria.models_zelador
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0021_reserva_acesso_liberado_reserva_bloco_apto_liberado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tipo_usuario',
            field=models.CharField(choices=[('sindico', 'Síndico'), ('porteiro', 'Porteiro'), ('morador', 'Morador'), ('zelador', 'Zelador'), ('admin', 'Administrador SaaS')], default='morador', max_length=20, verbose_name='Tipo de Usuário'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('RECLAMACAO', '📢 Reclamação'), ('MANUTENCAO', '🛠️ Manutenção'), ('MUDANCA', '🚚 Mudança')], max_length=20, verbose_name='Tipo de Solicitação'),
        ),
        migrations.CreateModel(
            name='AgendaZelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('data_manutencao', models.DateField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('realizada', models.BooleanField(default=False)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='ChecklistZelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('concluido', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio')),
                ('zelador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueZelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('quantidade_atual', models.IntegerField(default=0)),
                ('quantidade_minima', models.IntegerField(default=0)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio')),
            ],
        ),
        migrations.CreateModel(
            name='LivroOcorrenciaZelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('gravidade', models.CharField(choices=[('BAIXA', 'Baixa'), ('MEDIA', 'Média'), ('ALTA', 'Alta (Grave)')], default='BAIXA', max_length=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='ocorrencias_zelador/', validators=[portaria.models_zelador.validate_file_size])),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio')),
                ('zelador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrdemServicoZelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('ABERTA', 'Aberta'), ('EM_ANDAMENTO', 'Em Andamento'), ('CONCLUIDA', 'Concluída')], default='ABERTA', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='os_zelador/', validators=[portaria.models_zelador.validate_file_size])),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_encerramento', models.DateTimeField(blank=True, null=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio')),
                ('zelador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PrestadorServicoZelador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('empresa', models.CharField(blank=True, max_length=200, null=True)),
                ('documento', models.CharField(blank=True, max_length=50, null=True)),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio')),
                ('liberado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
