# Generated by Django 6.0.1 on 2026-02-19 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0021_aviso_arquivo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='morador',
            options={'ordering': ['bloco', 'apartamento'], 'verbose_name': 'Morador', 'verbose_name_plural': 'Moradores'},
        ),
    ]
