# Generated by Django 6.0.1 on 2026-05-05 20:30

import django.db.models.deletion
import portaria.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0022_alter_customuser_tipo_usuario_alter_solicitacao_tipo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('status', models.CharField(choices=[('Pendente', 'Pendente'), ('Em Andamento', 'Em Andamento'), ('Concluída', 'Concluída')], default='Pendente', max_length=20)),
                ('foto_conclusao', models.ImageField(blank=True, null=True, upload_to='os_zelador_conclusao/', validators=[portaria.models.validate_foto_conclusao])),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_conclusao', models.DateTimeField(blank=True, null=True)),
                ('solicitacao_origem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portaria.solicitacao')),
            ],
        ),
    ]
