# Generated by Django 6.0.1 on 2026-02-20 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0022_alter_morador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('aviso', '📢 Novo Aviso'), ('solicitacao', '📋 Nova Solicitação'), ('resposta_solicitacao', '💬 Resposta de Solicitação'), ('reserva', '📅 Reserva de Espaço')], max_length=30),
        ),
        migrations.CreateModel(
            name='AreaComum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Espaço')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição / Regras de Uso')),
                ('imagem', models.ImageField(blank=True, upload_to='areas_comuns/', verbose_name='Foto do Espaço')),
                ('capacidade', models.PositiveIntegerField(default=0, verbose_name='Capacidade (pessoas)')),
                ('horario_abertura', models.TimeField(default='08:00', verbose_name='Horário de Abertura')),
                ('horario_fechamento', models.TimeField(default='22:00', verbose_name='Horário de Fechamento')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível para Reservas')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas_comuns', to='portaria.condominio', verbose_name='Condomínio')),
            ],
            options={
                'verbose_name': 'Área Comum',
                'verbose_name_plural': 'Áreas Comuns',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data da Reserva')),
                ('horario_inicio', models.TimeField(verbose_name='Horário de Início')),
                ('horario_fim', models.TimeField(verbose_name='Horário de Término')),
                ('status', models.CharField(choices=[('PENDENTE', '🟡 Pendente'), ('APROVADA', '🟢 Aprovada'), ('RECUSADA', '🔴 Recusada'), ('CANCELADA', '⚫ Cancelada')], default='PENDENTE', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('motivo_recusa', models.TextField(blank=True, verbose_name='Motivo da Recusa')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data do Pedido')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='portaria.areacomum', verbose_name='Área Comum')),
                ('morador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='portaria.morador', verbose_name='Morador')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-data', '-horario_inicio'],
            },
        ),
    ]
