# Generated by Django 6.0.1 on 2026-02-25 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0023_alter_notificacao_tipo_areacomum_reserva'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='encomenda',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='encomendas', to='portaria.condominio', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='solicitacao',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solicitacoes', to='portaria.condominio', verbose_name='Condomínio'),
        ),
        migrations.AddField(
            model_name='visitante',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visitantes', to='portaria.condominio', verbose_name='Condomínio'),
        ),
        migrations.AlterField(
            model_name='solicitacao',
            name='tipo',
            field=models.CharField(choices=[('RECLAMACAO', '📢 Reclamação'), ('MANUTENCAO', '🛠️ Manutenção'), ('MUDANCA', '🚚 Mudança'), ('OUTRO', '📝 Outro')], max_length=20, verbose_name='Tipo de Solicitação'),
        ),
        migrations.CreateModel(
            name='Porteiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome Completo')),
                ('cargo', models.CharField(default='Porteiro', help_text='Ex: Porteiro, Zelador, Segurança', max_length=50, verbose_name='Cargo')),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='porteiros', to='portaria.condominio', verbose_name='Condomínio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='porteiro_perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Porteiro / Acesso',
                'verbose_name_plural': 'Porteiros e Acessos',
            },
        ),
    ]
