# Generated by Django 6.0.1 on 2026-05-05 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0023_ordemservico'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='condominio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portaria.condominio'),
        ),
    ]
