# Generated by Django 6.0.1 on 2026-05-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0025_ordemservico_zelador'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='feedback_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
