# Generated by Django 6.0.1 on 2026-05-15 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portaria', '0026_ordemservico_feedback_texto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificacao',
            name='tipo',
            field=models.CharField(choices=[('aviso', '📢 Novo Aviso'), ('solicitacao', '📋 Nova Solicitação'), ('resposta_solicitacao', '💬 Resposta de Solicitação'), ('reserva', '📅 Reserva de Espaço'), ('ocorrencia', '🚨 Nova Ocorrência'), ('geral', '🔔 Notificação Geral')], max_length=30),
        ),
    ]
